name: Inject Secrets
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Create config.js with Secrets
        run: |
          echo "const config = { GOOGLE_SCRIPT_URL: '${{ secrets.GOOGLE_SCRIPT_URL }}' };" > config.js
          
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add config.js
          git commit -m "Add config.js with secrets [skip ci]" || echo "No changes to commit"
          git push